development:
  adapter: postgresql
  encoding: unicode
  database: appname-dev
  pool: 5
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: appname-test
  pool: 5
  host: localhost
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: appname-prod
  pool: 5
  host: localhost
  password: